-- MyPerks seed data (run after schema.sql). Idempotent via ON CONFLICT.
-- Ported from the original Supabase project.

-- Demo account (password: perksdemo123)
insert into users (id, email, password_hash, display_name, locale, currency, lifestyle, onboarded, is_admin) values ('84de9afd-67be-492d-9977-563146eb3349', 'demo@myperks.app', '$2a$06$wH26fveIZPQX7Ho3.yn3fuRizWVUt4rLkffApDlPHIx1rHMXO/a7O', 'Demo', 'en', 'JPY', '{"dining": "eat_out", "family": "single", "activity": "indoor"}'::jsonb, true, true) on conflict (email) do nothing;

-- Badges
insert into badges (code, name, description, icon, criteria, sort_order) values ('first_step', 'First Step', 'Used your very first benefit', '🎉', '{"type": "uses", "count": 1}'::jsonb, 1) on conflict (code) do nothing;
insert into badges (code, name, description, icon, criteria, sort_order) values ('gourmet', 'Gourmet', 'Used 3 dining benefits', '🍜', '{"type": "scene_count", "count": 3, "scene": "eat"}'::jsonb, 2) on conflict (code) do nothing;
insert into badges (code, name, description, icon, criteria, sort_order) values ('health_master', 'Health Master', 'Used 3 fitness & learning benefits', '💪', '{"type": "scene_count", "count": 3, "scene": "move_learn"}'::jsonb, 3) on conflict (code) do nothing;
insert into badges (code, name, description, icon, criteria, sort_order) values ('explorer', 'Explorer', 'Tried a benefit from all four life scenes', '🧭', '{"type": "distinct_scenes", "count": 4}'::jsonb, 4) on conflict (code) do nothing;
insert into badges (code, name, description, icon, criteria, sort_order) values ('big_saver', 'Big Saver', 'Saved ¥10,000 in total', '💰', '{"type": "total_saved", "amount": 10000}'::jsonb, 5) on conflict (code) do nothing;

-- Benefits
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('b5f96f7c-4a88-43da-8f7a-b9e8d0e5ec0e', 'eat'::scene, 'Lunch Coupon 10% Off', 'Show the in-app coupon at the register', 'Partner Cafés', null, 10, 'JPY', 'Get 10% off lunch at participating cafés near the office, every weekday.', 35.6595, 139.7005, 'Shibuya', 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('2d07409a-9775-46a3-b471-921f5096fc08', 'eat'::scene, 'Daily Lunch Subsidy', 'Pay with your meal card to auto-apply', 'Company Cafeteria', 500, null, 'JPY', 'The company covers ¥500 of your lunch each working day.', 35.6605, 139.701, 'Shibuya', 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('624e44e0-9f68-42cf-b3a5-c24721ab2f21', 'eat'::scene, 'Partner Restaurant Dinner', 'Mention your employee membership when booking', 'Partner Restaurants', null, 15, 'JPY', '15% off dinner at a curated list of partner restaurants.', 35.662, 139.699, 'Shibuya', 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('5bffc423-8397-4c7e-98ce-1bebe0da2c72', 'move_learn'::scene, 'Gym: First Month Free', 'Sign up with the corporate code in the app', 'Anytime Fitness', 8000, null, 'JPY', 'Your first month of gym membership is fully covered, then discounted monthly.', 35.658, 139.6985, 'Shibuya', 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('6a71e38f-5f96-48f8-add2-bfa4b4e5c254', 'move_learn'::scene, 'Book Purchase Stipend', 'Submit your receipt in the expense app', 'Any bookstore', 3000, null, 'JPY', 'Up to ¥3,000 per month reimbursed for books that support your growth.', null, null, NULL, 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('bd695760-0f87-49c5-ae79-0ef2fcadb74b', 'move_learn'::scene, 'Certification Allowance', 'Apply via HR after passing your exam', 'HR Department', 30000, null, 'JPY', 'Earn up to ¥30,000 when you pass an approved professional certification.', null, null, NULL, 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('3fdf0e2f-388d-4fa3-b683-8d581f310e6d', 'relax_play'::scene, 'Movie Tickets ¥1,000', 'Buy through the member portal link', 'Cinema Partners', 900, null, 'JPY', 'Watch movies for a flat ¥1,000 (save ~¥900 per ticket) at partner cinemas.', 35.6585, 139.702, 'Shibuya', 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('b6c43c67-1d59-4a47-a49b-b33c8ba008af', 'relax_play'::scene, 'Hotel Preferential Rates', 'Book via the corporate travel benefits page', 'Partner Hotels', null, 20, 'JPY', '20% off stays at partner hotels nationwide for you and your family.', 35.67, 139.703, 'Shinjuku', 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('26f5d916-4fa5-4ba1-a91f-ce4b3655bc73', 'relax_play'::scene, 'Refresh Leave', 'Request the day in the leave system', 'HR Department', null, null, 'JPY', 'Take an extra paid day off each quarter to recharge.', null, null, NULL, 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('35aa40bc-9647-4367-952d-3edca5d48c50', 'life_events'::scene, 'Congratulation & Condolence Money', 'Notify HR of the life event to receive payment', 'HR Department', 30000, null, 'JPY', 'A monetary gift from the company for major life events such as marriage or bereavement.', null, null, NULL, 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('a0630134-7b73-4409-a77c-36a2cef54fc4', 'life_events'::scene, 'Childcare Support', 'Enroll through the family benefits form', 'HR Department', 20000, null, 'JPY', 'Up to ¥20,000 per month to help with childcare costs.', null, null, NULL, 'en', true) on conflict (id) do nothing;
insert into benefits (id, scene, title, action, vendor, amount, discount_pct, currency, details, lat, lng, area, base_locale, published) values ('9b70c397-6cef-468d-9c6f-69045a5e0e1e', 'life_events'::scene, 'Nursing Care Leave', 'Apply via HR with the care plan', 'HR Department', null, null, 'JPY', 'Paid leave to care for a family member in need of nursing support.', null, null, NULL, 'en', true) on conflict (id) do nothing;

-- Benefit translations
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('b5f96f7c-4a88-43da-8f7a-b9e8d0e5ec0e', 'ja', 'ランチクーポン 10%オフ', 'レジでアプリ内クーポンを提示', '平日のランチが対象カフェで10%オフになります。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('2d07409a-9775-46a3-b471-921f5096fc08', 'ja', 'ランチ補助（毎日）', '食事カードで支払うと自動適用', '会社が毎営業日のランチ代を500円補助します。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('624e44e0-9f68-42cf-b3a5-c24721ab2f21', 'ja', '提携レストランのディナー', '予約時に社員会員であることを伝える', '厳選した提携レストランのディナーが15%オフ。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('5bffc423-8397-4c7e-98ce-1bebe0da2c72', 'ja', 'ジム：初月無料', 'アプリの法人コードで入会', 'ジムの初月会費が無料、以降も割引価格に。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('6a71e38f-5f96-48f8-add2-bfa4b4e5c254', 'ja', '書籍購入補助', '経費アプリでレシートを提出', '成長につながる書籍代を月3,000円まで補助。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('bd695760-0f87-49c5-ae79-0ef2fcadb74b', 'ja', '資格取得手当', '合格後にHRへ申請', '承認された資格に合格すると最大30,000円を支給。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('3fdf0e2f-388d-4fa3-b683-8d581f310e6d', 'ja', '映画チケット 1,000円', '会員ポータルのリンクから購入', '提携映画館で1本1,000円（1枚あたり約900円お得）。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('b6c43c67-1d59-4a47-a49b-b33c8ba008af', 'ja', 'ホテル優待', '法人トラベル特典ページから予約', '全国の提携ホテルがご家族も20%オフ。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('26f5d916-4fa5-4ba1-a91f-ce4b3655bc73', 'ja', 'リフレッシュ休暇', '休暇システムで申請', '四半期ごとに有給のリフレッシュ休暇を1日取得できます。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('35aa40bc-9647-4367-952d-3edca5d48c50', 'ja', '慶弔見舞金', 'ライフイベントをHRに連絡して受給', '結婚や不幸などの人生の節目に会社から支給される金銭。', '日本のビジネス文化では、結婚・出産や身内の不幸の際に会社から「慶弔見舞金」が支給される慣習があります。') on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('a0630134-7b73-4409-a77c-36a2cef54fc4', 'ja', '育児サポート', '家族向け特典フォームから登録', '育児費用を月最大20,000円まで補助。', NULL) on conflict (benefit_id, locale) do nothing;
insert into benefit_translations (benefit_id, locale, title, action, details, context_tip) values ('9b70c397-6cef-468d-9c6f-69045a5e0e1e', 'ja', '介護休暇', 'ケアプランを添えてHRへ申請', '看護・介護が必要な家族のための有給休暇。', '日本では介護を理由とした休暇制度が法律でも定められており、会社独自の上乗せ支援がある場合があります。') on conflict (benefit_id, locale) do nothing;
